Cleanup UI code after Vaadin migration
eclipse/hawkbit pull request #1027
Opened 2020-10-14 05:52 UTC by blomark

Refactored code and removed duplications in WindowController classes and Layout classes

This PR also contains a minor bugfix when updating an existing distribution set a duplicate error is no longer shown

2020-10-14 06:41 UTC, schabdo commented
@hawkbit-bot verify please

2020-11-02 02:01 UTC, bogdan-bondar requested changes
Couple of small comments, but otherwise great job! ;)

2020-11-02 11:13 UTC, blomark commented on hawkbit-ui/src/main/java/org/eclipse/hawkbit/ui/common/data/filters/DsFilterParams.java
> +public class DsFilterParams implements Serializable {
I would suggest to discuss this independantly of this PR

2020-11-03 18:35 UTC, bogdan-bondar approved these changes
Thanks a lot @blomark!

2020-11-05 08:59 UTC, merged